version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: express-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
      - mongodb-data:/data/db

  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://root:examplepassword@mongodb:27017/mydb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongodb-data:
